# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2230f49667e788273ee64cf1e51b0141efd81c2266da2eec8d42079d722806fb26ef18812c932ca5a5cf4780b5f30432513e6ab305d516fd0851f07e1bc1c23a

test:
  secret_key_base: d53999a6b51d87175c0a6a084a994296536821afdc9adbf553aac1e14738b2ea72362160d5c39b4c26f4178805347b42b6b3d7c7fb3f405daf4656ded53c9884

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
